version: '2'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=trocacasa

  web:
    build: .
    env_file:
      - .env
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
      - redis
    entrypoint: ["sh", "/usr/src/app/docker-entrypoint.sh"]
